-- CreateTable
CREATE TABLE "CPU" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "manufacturer" TEXT NOT NULL,
    "brand" TEXT NOT NULL,
    "vendor" TEXT NOT NULL,
    "family" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "stepping" TEXT NOT NULL,
    "revision" TEXT,
    "voltage" TEXT,
    "speed" INTEGER NOT NULL,
    "speedMin" INTEGER,
    "speedMax" INTEGER,
    "governor" TEXT,
    "cores" INTEGER NOT NULL,
    "physicalCores" INTEGER NOT NULL,
    "performanceCores" INTEGER NOT NULL,
    "efficiencyCores" INTEGER NOT NULL,
    "processors" INTEGER NOT NULL,
    "socket" TEXT,
    "flags" TEXT NOT NULL,
    "virtualization" BOOLEAN NOT NULL,
    "avgLoad" REAL NOT NULL,
    "currentLoad" REAL NOT NULL,
    "currentLoadUser" REAL NOT NULL,
    "currentLoadSystem" REAL NOT NULL,
    "currentLoadNice" REAL NOT NULL,
    "currentLoadIdle" REAL NOT NULL,
    "currentLoadIrq" REAL NOT NULL,
    "currentLoadSteal" REAL NOT NULL,
    "currentLoadGuest" REAL NOT NULL,
    "rawCurrentLoad" INTEGER NOT NULL,
    "rawCurrentLoadUser" INTEGER NOT NULL,
    "rawCurrentLoadSystem" INTEGER NOT NULL,
    "rawCurrentLoadNice" INTEGER NOT NULL,
    "rawCurrentLoadIdle" INTEGER NOT NULL,
    "rawCurrentLoadIrq" INTEGER NOT NULL,
    "rawCurrentLoadSteal" INTEGER NOT NULL,
    "rawCurrentLoadGuest" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
